### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by alreadyarrived** [Humorloos/SMR#6]
Hello, I'm getting an error when importing:

`Import failed.
Traceback (most recent call last):
  File "aqt\importing.py", line 339, in importFile
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\61346236\xminder.py", line 49, in run
    self.importSheets(selectedSheets)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\61346236\xminder.py", line 65, in importSheets
    self.importMap(sheetImport)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\61346236\xminder.py", line 106, in importMap
    self.col.decks.current()['mid'] = xModel['id']
TypeError: 'NoneType' object is not subscriptable`

What should I do here?

Screenshot of my xmind8 map: https://i.imgur.com/1YpyOrK.png

**Comment by alreadyarrived** [comment]
Just restarted anki and it somehow worked!
